FROM ubuntu:bionic AS  build-base

RUN apt-get update && apt-get install -y build-essential cmake

COPY . /src/NITCbase/

WORKDIR /src/NITCbase/Frontend_Interface/

RUN cmake --clean-first . && make

# Use second docker image for the Frontend-Executable and Volumes
FROM ubuntu:bionic

WORKDIR /opt/NITCbase/Frontend_Interface/

COPY --from=build-base /src/NITCbase/Frontend_Interface ./

CMD [ "./Frontend-Interface" ]