FROM ubuntu:bionic AS  build-base

RUN apt-get update && apt-get install -y build-essential cmake

COPY . /src/NITCbase/

WORKDIR /src/NITCbase/XFS_Interface/

RUN cmake --clean-first . && make

# Use second docker image for the XFS-Executable and Volumes
FROM ubuntu:bionic

WORKDIR /opt/NITCbase/XFS_Interface/

COPY --from=build-base /src/NITCbase/XFS_Interface/XFS-Interface ./

CMD [ "./XFS-Interface" ]